version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - dependency-update
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "proceeding"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    labels:
      - dependency-update
