# This workflow will build Cerberus Executable and Uploads the generated binary to release

name: Compile And Assemble

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Binary Executable
      run: mvn clean package site surefire-report:report compile assembly:single