name: PR-Automation

on:
  pull_request_target:
    branches: [ master, development]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean build pitest shadowJar 
    - name: Fail it when failed due to quality checks 
      if: ${{ failure() }}
      uses: peter-evans/close-pull@v1.1.2
      with: 
        comment: "Many thanks for your contribution. Our automated PR checks picked up some great opportunities to avoid a bounce-back from continuous integration and improve quality and early defect detection. We auto-rejected the PR so that you can work on this in your fork and re-submit. Our maintainer team would be happy to assist you in making a successful PR if you want any further support – just let us know how we can help."

      
